# Generated by Django 5.1.7 on 2025-04-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('OPERATOR', 'Operator'), ('MANAGER', 'Manager'), ('ADMIN', 'Admin')], default='CLIENT', max_length=10),
        ),
    ]
