# Generated by Django 5.1.7 on 2025-04-14 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_account_account_number_account_enterprise_user_banks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='bic',
        ),
    ]
