# Generated by Django 5.1.7 on 2025-04-14 04:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_bank_bic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(default=uuid.uuid4, max_length=20, unique=True),
        ),
    ]
