# Generated by Django 5.1.7 on 2025-04-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_account_account_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='user',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='user',
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.DeleteModel(
            name='Transfer',
        ),
    ]
