# Generated by Django 5.1.7 on 2025-04-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_lease_approved_by_lease_status_lease_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0.05, max_digits=5),
        ),
    ]
