# Generated by Django 5.1.7 on 2025-04-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('OPERATOR', 'Operator'), ('MANAGER', 'Manager'), ('ADMIN', 'Admin'), ('SPECIALIST', 'Specialist')], default='CLIENT', max_length=20),
        ),
    ]
